import test from 'node:test';
import assert from 'node:assert/strict';
import {createHarness,seed} from './gas-harness.mjs';
const student={Student_ID:'001',First_Name:'สมชาย',Last_Name:'ทดสอบ',Grade_Level:'ม.3',Room:'1',Category:'ปกติ'};
function ok(res){assert.equal(res.error,undefined,res.error);return res;}
function ready(h,c){let s=h.call('data',c);ok(h.call('keys/update',{...c,exam_items_key:s.db.Exam_Items_Key.map(k=>({...k,Answer_Key:'1'}))}));ok(h.call('students/save',{...c,student}));ok(h.call('exams/update_targets',{...c,action:'add_student',payload_value:'001'}));}
test('new exam exposes all 40 editable keys before any responses',()=>{const h=createHarness(),c=seed(h);const s=ok(h.call('data',c));assert.equal(s.db.Exam_Items_Key.length,40);assert.equal(s.analysis.summary.total_questions,40);assert.equal(s.analysis.summary.student_count,0);assert.equal(s.db.Exam_Items_Key[39].Q_Num,40);});
test('health reports a ready registry and number of connected years',()=>{const h=createHarness();assert.deepEqual(JSON.parse(JSON.stringify(ok(h.call('health')))),{status:'ready',version:3,registry_sheet_id:h.properties.get('MASTER_SHEET_ID'),year_count:0,can_create_spreadsheet:true});seed(h);assert.equal(ok(h.call('health')).year_count,1);});
test('a year can initialize an existing Google Sheet ID instead of creating a file',()=>{const h=createHarness();const sheet=h.context.SpreadsheetApp.create('existing');const before=h.stats.creates;const s=ok(h.call('years/add',{year:'2570',sheet_id:sheet.getId()}));assert.equal(h.stats.creates,before);assert.equal(s.db.Config_Metadata.Academic_Years[0].sheet_id,sheet.getId());assert.ok(sheet.getSheetByName('Subjects'));assert.ok(sheet.getSheetByName('Responses'));});
test('failed sheet creation does not add a broken year to the registry',()=>{const h=createHarness();h.context.SpreadsheetApp.create=()=>{throw new Error('permission denied');};assert.match(h.call('years/add',{year:'2570'}).error,/สร้าง Google Sheet ใหม่ไม่ได้/);assert.equal(ok(h.call('health')).year_count,0);});
test('legacy scalar units are normalized and subjects save with learning units',()=>{const h=createHarness(),c=seed(h);let s=ok(h.call('data',c));const yearSheet=h.files.get(s.db.Config_Metadata.Academic_Years[0].sheet_id),subjects=yearSheet.getSheetByName('Subjects');subjects.rows[1][3]='1';s=ok(h.call('data',c));assert.deepEqual(s.db.Config_Metadata.Subjects[0].units,[]);s=ok(h.call('subjects/save',{...c,subject:{code:'SCI',name:'วิทยาศาสตร์',grade_level:'ม.3',units:[{unit_no:'1',unit_name:'แรงและการเคลื่อนที่'}]}}));assert.equal(s.db.Config_Metadata.Subjects[0].units[0].unit_name,'แรงและการเคลื่อนที่');});
test('save keys preserves zero weight, Thai indicator and Bloom across fresh sheet reads',()=>{const h=createHarness(),c=seed(h);let s=h.call('data',c);const keys=s.db.Exam_Items_Key.map(k=>({...k,Answer_Key:'ก',Standard_Code:'ว 1.1 ม.3/1',Bloom_Taxonomy:'การวิเคราะห์'}));keys[0].Weight=0;ok(h.call('keys/update',{...c,exam_items_key:keys}));h.cache.clear();s=ok(h.call('data',c));assert.equal(s.db.Exam_Items_Key[0].Weight,0);assert.equal(s.db.Exam_Items_Key[0].Answer_Key,'1');assert.equal(s.db.Exam_Items_Key[39].Standard_Code,'ว 1.1 ม.3/1');assert.equal(s.db.Exams_Header[0].Total_Score,39);});
test('fast entry persists all 40 answers plus stable submission ID and timestamp',()=>{const h=createHarness(),c=seed(h);ready(h,c);let s=ok(h.call('responses/fast-entry',{...c,student_id:'001',raw_answers:Object.fromEntries(Array.from({length:40},(_,i)=>[i+1,'1']))}));assert.equal(s.analysis.summary.mean_score,40);const id=s.db.Student_Responses[0].Submission_ID;h.cache.clear();s=ok(h.call('data',c));assert.equal(s.db.Student_Responses[0].Submission_ID,id);assert.equal(s.db.Student_Responses[0].Raw_Answers['40'],'1');assert.match(s.db.Student_Responses[0].Timestamp,/^\d{4}-/);assert.equal(s.db.Students_Roster[0].Student_ID,'001');});
test('separate years isolate sheets, students, exams and answers; selection does not write shared state',()=>{const h=createHarness(),a=seed(h,{year:'2568'});ready(h,a);const b=seed(h,{year:'2569'});const s=ok(h.call('data',b));assert.equal(s.db.Students_Roster.length,0);assert.notEqual(s.exam_id,a.exam_id);assert.equal(ok(h.call('data',a)).db.Students_Roster.length,1);h.resetStats();ok(h.call('years/select',{year:'2568'}));ok(h.call('exams/select',b));assert.equal(h.stats.writes,0);});
test('delete exam removes linked rows; newly created IDs never collide',()=>{const h=createHarness(),a=seed(h);ready(h,a);ok(h.call('responses/string-entry',{...a,student_id:'001',answer_string:'1'.repeat(40)}));ok(h.call('exams/delete',a));const db=h.call('export/json',{year:a.year}).data;assert.equal(db.Exam_Parts.length,0);assert.equal(db.Exam_Items_Key.length,0);assert.equal(db.Student_Responses.length,0);const next=ok(h.call('exams/add',{year:a.year,exam:{Subject_Code:'SCI',Exam_Title:'ใหม่',parts:[{name:'ตอนเดียว',qs:2,score:2}]}}));assert.notEqual(next.exam_id,a.exam_id);});
test('invalid keys fail before writes; unauthenticated API cannot read data',()=>{const h=createHarness(),c=seed(h),s=h.call('data',c);h.resetStats();assert.ok(h.call('keys/update',{...c,exam_items_key:[]}).error);assert.equal(h.stats.writes,0);assert.ok(h.call('data',c,'bad').error);assert.ok(h.call('keys/update',{...c,exam_items_key:s.db.Exam_Items_Key.map(k=>({...k,Weight:-1}))}).error);});
test('room assignment never includes same room from another grade',()=>{const h=createHarness(),c=seed(h);ok(h.call('students/bulk_save',{...c,students:[student,{...student,Student_ID:'002',Grade_Level:'ม.2'}]}));const s=ok(h.call('exams/update_targets',{...c,action:'add_room',payload_value:'1'}));assert.deepEqual(s.db.Exams_Header[0].Target_Students,['001']);});
test('removing year keeps its original spreadsheet for recovery',()=>{const h=createHarness(),c=seed(h);const before=h.files.size;const s=ok(h.call('years/delete',c));assert.equal(h.files.size,before);assert.equal(s.db.Config_Metadata.Academic_Years.length,0);});
test('unavailable sheet reports error instead of an empty database',()=>{const h=createHarness(),c=seed(h);const s=h.call('data',c);h.files.delete(s.db.Config_Metadata.Academic_Years[0].sheet_id);h.cache.clear();assert.match(h.call('data',c).error,/unavailable/);});
test('subject deletion with linked exams is rejected',()=>{const h=createHarness(),c=seed(h);assert.ok(h.call('subjects/delete',{...c,code:'SCI'}).error);});
test('all-unverified responses return a complete empty analysis',()=>{const h=createHarness();const a=h.context.calculateExamAnalysis({},[],[{Q_Num:1,Weight:1,Answer_Key:'1'}],[{Is_Verified:false}],[]);assert.equal(a.summary.student_count,0);assert.equal(a.student_scores.length,0);});
test('known scores give correct difficulty, discrimination and KR20; weighted equivalent is alpha',()=>{
 const h=createHarness();const keys=[1,2].map(Q_Num=>({Q_Num,Part_ID:1,Answer_Key:'1',Weight:1}));
 const answers=[['1','1'],['1','1'],['1','2'],['2','2']];
 const responses=answers.map((a,i)=>({Student_ID_Matched:String(i),Is_Verified:true,Raw_Answers:{1:a[0],2:a[1]}}));
 const a=h.context.calculateExamAnalysis({},[{Part_ID:1}],keys,responses,[]);
 assert.equal(a.summary.mean_score,1.25);assert.equal(a.items_analysis[0].Difficulty_p,.75);assert.equal(a.items_analysis[1].Difficulty_p,.5);assert.equal(a.items_analysis[0].Discrimination_r,1);assert.equal(a.summary.reliability_kr20,.7273);
 keys[1].Weight=2;const b=h.context.calculateExamAnalysis({},[{Part_ID:1}],keys,responses,[]);assert.equal(b.summary.reliability_kr20,null);assert.equal(b.summary.reliability,.5926);
});
test('blank key does not award points for a blank response, and zero weight retains item correctness',()=>{const h=createHarness();const a=h.context.calculateExamAnalysis({},[],[{Q_Num:1,Weight:0,Answer_Key:'1'},{Q_Num:2,Weight:1,Answer_Key:''}],[{Student_ID_Matched:'1',Is_Verified:true,Raw_Answers:{1:'1',2:''}}],[]);assert.equal(a.student_scores[0].Total_Score,0);assert.equal(a.items_analysis[0].Difficulty_p,1);assert.equal(a.summary.reliability,null);});
